server:
  port: 8080
  servlet:
    context-path: /bookkeeping

spring:
  profiles:
    active: local
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 200
      minimum-idle: 20

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    default-executor-type: reuse
    use-generated-keys: true

logging:
  level:
    root: info
    com.bookkeeping: info


